### ISSUE TITLE
Desktop client ignores "--injector-credentials" option

### ISSUE THREAD

**Issue by ivilata** [equalitie/ouinet#14]
When testing commit 276c22d3 on GNU/Linux Docker with credentials in the injector, adding the exact same value for the `injector-credentials` in `ouinet-client.conf` doesn't seem to have effect in the client, and the browser keeps on asking authentication for the proxy until it is entered. Completely disabling the option in the client yields the same result. After the correct credentials are entered at the browser, everything seems to work as expected.

**Comment by inetic** [comment]
Fixed in commit [6aa7ef455](https://github.com/equalitie/ouinet/commit/6aa7ef45561e789659325433b19eb42d5518b4dc)
