### ISSUE TITLE
Do not require GNUnet when not using it

### ISSUE THREAD

**Issue by ivilata** [equalitie/ouinet#7]
As indicated in #6, not running GNUnet services makes the client hang during boot. Forcing users to start the services when not using it is involved since a different, concurrent shell must be run for executing the ``start-gnunet-*.sh`` script.

It would be nice to avoid the client from using GNUnet if no such endpoints are being used in its configuration.

**Comment by inetic** [comment]
Fixed in [this commit](https://github.com/equalitie/ouinet/commit/b2d0f00c9f8e31c90df0b7b5e2b9bd439e692c99). [Here in particular](https://github.com/equalitie/ouinet/commit/b2d0f00c9f8e31c90df0b7b5e2b9bd439e692c99#diff-34f48ad91ac6c202ac60b0348ae90e30R412).
